name: auto-run-build
on: [push]
jobs:
  auto-run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - uses: swinton/commit@v2.0.0
        with:
          files: build
          commit-message:  'auto build'
      - uses: ludeeus/action-push@0.0.1